name: Validate i18n JSON file

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validateJSON:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: walbo/validate-json@v1.1.0
        with:
          files: public/locales/**/*.json

          # optional, defaults to `$schema` in your JSON file
          schema: schemas/schema.json

          # optional, default: draft-04
          schema-version: draft-07

          # optional, default: false
          print-valid-files: false

          # optional, default: false
          fail-on-missing-schema: false

          # optional, default: true
          strict: true

          # optional, default: false
          allow-matching-properties: false

          # optional, default: true
          allow-union-types: true
